wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/main.py
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.39.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720749115.445226
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 105
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 105
      3:
      - 17
      - 23
      - 37
      4: 3.10.13
      5: 0.16.0
      6: 4.39.2
      8:
      - 5
      13: linux-x86_64
width:
  desc: null
  value: 1000
depth:
  desc: null
  value: 2
converge_acc:
  desc: null
  value: 0.999
train_type:
  desc: null
  value: warm
model:
  desc: null
  value: resnet18
dataset:
  desc: null
  value: cifar10
optimizer_type:
  desc: null
  value: sgd
rho:
  desc: null
  value: 0.1
norm:
  desc: null
  value: bn
weight_decay:
  desc: null
  value: 0
batch_size:
  desc: null
  value: 128
test_batch_size:
  desc: null
  value: 1024
learning_rate:
  desc: null
  value: 0.001
momentum:
  desc: null
  value: 0.9
gpu:
  desc: null
  value: 1
num_chunks:
  desc: null
  value: 50
num_workers:
  desc: null
  value: 0
seed:
  desc: null
  value: 2022
sp_lambda:
  desc: null
  value: 0.1
dash_lambda:
  desc: null
  value: 0.3
dash_alpha:
  desc: null
  value: 0.3
l2_init_lambda:
  desc: null
  value: 0.01
max_epoch:
  desc: null
  value: 10000
sota:
  desc: null
  value: false
project_name:
  desc: null
  value: resnet18-cifar10
