wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/temp.py
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.39.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719982314.809949
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      3:
      - 23
      4: 3.10.13
      5: 0.16.0
      6: 4.39.2
      8:
      - 5
      13: linux-x86_64
epoch:
  desc: null
  value: 100
train_type:
  desc: null
  value: random
model:
  desc: null
  value: resnet18
dataset:
  desc: null
  value: cifar10
optimizer_type:
  desc: null
  value: sgd
norm:
  desc: null
  value: bn
weight_decay:
  desc: null
  value: 0
batch_size:
  desc: null
  value: 128
test_batch_size:
  desc: null
  value: 1024
learning_rate:
  desc: null
  value: 0.001
momentum:
  desc: null
  value: 0.9
activation:
  desc: null
  value: ReLU
gpu:
  desc: null
  value: 4
seed:
  desc: null
  value: 2021
num_chunks:
  desc: null
  value: 2
project_name:
  desc: null
  value: noise vs warm
