wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/main.py
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.39.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720749104.01958
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 105
      3:
      - 23
      4: 3.10.13
      5: 0.16.0
      6: 4.39.2
      8:
      - 5
      13: linux-x86_64
